# Generated by Django 4.2.18 on 2025-01-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Barn Manager', 'Barn Manager'), ('Horse Owner', 'Horse Owner'), ('Rider', 'Rider'), ('Staff Member', 'Staff Member')], max_length=20, null=True),
        ),
    ]
