# Generated by Django 4.2.18 on 2025-02-06 08:30

from django.db import migrations

def populate_user_profile(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    User = apps.get_model('auth', 'User') 
    
    for profile in Profile.objects.all():
        try:
            user = User.objects.get(username=profile.user.username)
            profile.user = user
            profile.save()
        except User.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_user'),
    ]

    operations = [
        migrations.RunPython(populate_user_profile, reverse_code=migrations.RunPython.noop),
    ]
