# Generated by Django 4.2.18 on 2025-02-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('Horse', 'Horse'), ('Equipment', 'Equipment'), ('Clothing', 'Clothing'), ('Machinery/Auto', 'Machinery/Auto'), ('Animal', 'Animal'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
