# Generated by Django 4.2.18 on 2025-03-20 16:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_communityevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
