# Generated by Django 4.2.18 on 2025-03-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_announcement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
