# Generated by Django 4.2.18 on 2025-02-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_announcement_temp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='temp_field',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='temp_field',
        ),
    ]
