# Generated by Django 4.2.18 on 2025-02-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
