# Generated by Django 4.2.18 on 2025-02-08 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Mare', 'Mare'), ('Gelding', 'Gelding'), ('Stallion', 'Stallion')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='horses/images')),
                ('barn_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horse_barn_manager', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horse_owner', to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horse_rider', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ManyToManyField(related_name='horse_staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
