# Generated by Django 4.2.18 on 2025-02-06 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('horses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horseprofile',
            name='description',
        ),
        migrations.AlterField(
            model_name='horseprofile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horse_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
