# Generated by Django 4.2.18 on 2025-02-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horseprofile',
            name='description',
        ),
    ]
