# Generated by Django 4.2.18 on 2025-02-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0002_remove_horseprofile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horseprofile',
            name='temp_field',
            field=models.CharField(blank=True, default='temporary', max_length=20, null=True),
        ),
    ]
