# Generated by Django 5.1.7 on 2025-03-24 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0003_alter_horseprofile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='horseprofile',
            name='last_cared_for_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horseprofile',
            name='last_ridden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horseprofile',
            name='most_recent_care',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horses_cared_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horseprofile',
            name='most_recent_ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horses_ridden', to=settings.AUTH_USER_MODEL),
        ),
    ]
