# Generated by Django 4.2.18 on 2025-03-21 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeding_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingchart',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedingchart',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
