# Generated by Django 4.2.18 on 2025-03-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_schedule', '0002_remove_exerciseschedule_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisescheduleitem',
            name='time_category',
            field=models.CharField(choices=[('am', 'AM'), ('pm', 'PM'), ('additional', 'Additional')], default='am', max_length=20),
        ),
    ]
