# Generated by Django 4.2.18 on 2025-03-02 23:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_schedule', '0003_exercisescheduleitem_time_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisescheduleitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
