# Generated by Django 4.2.18 on 2025-03-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_schedule', '0007_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
    ]
