# Generated by Django 4.2.18 on 2025-02-15 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
