# Generated by Django 4.2.18 on 2025-02-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_event_approved_event_favorited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
