# Generated by Django 4.2.18 on 2025-02-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0001_initial'),
        ('competitions', '0003_event_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='horses',
            field=models.ManyToManyField(blank=True, related_name='events', to='horses.horseprofile'),
        ),
    ]
