# Generated by Django 4.2.18 on 2025-02-20 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0001_initial'),
        ('competitions', '0004_event_horses'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventHorse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, max_length=200, null=True)),
                ('results', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.event')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horses.horseprofile')),
            ],
            options={
                'unique_together': {('event', 'horse', 'class_name')},
            },
        ),
    ]
