# Generated by Django 4.2.18 on 2025-02-20 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_eventhorse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventhorse',
            old_name='class_name',
            new_name='class_details',
        ),
        migrations.AlterUniqueTogether(
            name='eventhorse',
            unique_together=set(),
        ),
    ]
