# Generated by Django 4.2.18 on 2025-02-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventhorse',
            name='performance_rating',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
