# Generated by Django 4.2.18 on 2025-02-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_eventhorse_jump_height_eventhorse_number_of_faults'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventhorse',
            name='jump_height_str',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
