# Generated by Django 4.2.18 on 2025-02-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_eventhorse_jump_height_str'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
